Repository NNPDF/yadism, pull requests merged in 2020-07, with the labels that each got.

#65 Docs: more on overall descriptions
  .github/contributing.md
  README.md
  docs/sphinx/source/dev-tools/benchmark-runner.rst
  docs/sphinx/source/dev-tools/benchmarks.rst
  docs/sphinx/source/dev-tools/regression-tests.rst
  docs/sphinx/source/dev-tools/tests.rst
  docs/sphinx/source/dev-tools/unit-tests.rst
  docs/sphinx/source/package-structure/ESF.rst
  docs/sphinx/source/package-structure/runner.rst
  docs/sphinx/source/shared/abbreviations.rst
  docs/sphinx/source/theory/heavy-flavors.rst
  src/yadism/coupling_constants.py
  src/yadism/runner.py
Labels: documentation

#67 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#68 Rework benchmarking system
  .gitattributes
  .github/workflows/benchmarks.yml
  .github/workflows/regression.yml
  .github/workflows/unittests.yml
  benchmarks/aux/__init__.py
  benchmarks/benchmark_against_apfel.py
  benchmarks/benchmark_against_qcdnum.py
  benchmarks/data/.gitignore
  benchmarks/data/observables.py
  benchmarks/data/regression-observables.py
  benchmarks/data/theory.py
  benchmarks/generatePDF/.gitignore
  benchmarks/generatePDF/generatePDF.py
  benchmarks/generatePDF/templatePDF/templatePDF.dat
  benchmarks/generatePDF/templatePDF/templatePDF.info
  benchmarks/navigator
  benchmarks/navigator.py
  benchmarks/regression.py
  benchmarks/sandbox.py
  benchmarks/setup.py
  benchmarks/storage/apfel-input.json
  benchmarks/storage/regression.json
  benchmarks/theory_template.yaml
  benchmarks/yadmark/__init__.py
  benchmarks/yadmark/data/__init__.py
  benchmarks/yadmark/data/observables.py
  benchmarks/yadmark/data/theories.py
  benchmarks/yadmark/db_interface.py
  benchmarks/yadmark/external/__init__.py
  benchmarks/yadmark/external/apfel_utils.py
  benchmarks/yadmark/external/apfel_xg.yaml
  benchmarks/yadmark/external/qcdnum_utils.py
  benchmarks/yadmark/mode_selector.py
  benchmarks/yadmark/navigator/__init__.py
  benchmarks/yadmark/navigator/df_list.py
  benchmarks/yadmark/navigator/navigator.py
  benchmarks/yadmark/toyLH.py
  benchmarks/yadmark/utils.py
  src/yadism/observable_name.py
  src/yadism/runner.py
  test_requirements.txt
Labels: refactor, test

#70 Neutral Current corrections
  benchmarks/benchmark_against_apfel.py
  benchmarks/regression.py
  benchmarks/sandbox.py
  benchmarks/setup.py
  benchmarks/yadmark/db_interface.py
  benchmarks/yadmark/external/apfel_utils.py
  setup.py
  src/yadism/coupling_constants.py
  src/yadism/observable_name.py
  src/yadism/runner.py
  src/yadism/sf.py
  src/yadism/structure_functions/__init__.py
  src/yadism/structure_functions/esf.py
  src/yadism/structure_functions/f2_asymptotic.py
  src/yadism/structure_functions/f2_heavy.py
  src/yadism/structure_functions/f_total.py
  src/yadism/structure_functions/fl_asymptotic.py
  src/yadism/structure_functions/fl_heavy.py
  src/yadism/structure_functions/fl_light.py
  src/yadism/structure_functions/nc/__init__.py
  src/yadism/structure_functions/nc/f2_asy.py
  src/yadism/structure_functions/nc/f2_heavy.py
  src/yadism/structure_functions/nc/f2_light.py
  src/yadism/structure_functions/nc/fl_asy.py
  src/yadism/structure_functions/nc/fl_heavy.py
  src/yadism/structure_functions/nc/fl_light.py
  src/yadism/structure_functions/partonic_channel.py
  tests/test_observable_name.py
  tests/test_structure_function.py
Labels: enhancement, physics, refactor
