Repository NNPDF/yadism, pull requests merged in 2023-11, with the labels that each got.

#195 Numerical FONLL
  benchmarks/runners/apfel_.py
  benchmarks/runners/sandbox.py
  extras/fonll_hq_treatment/utils.py
  poetry.lock
  pyproject.toml
  src/yadbox/runcards/theory.py
  src/yadism/coefficient_functions/__init__.py
  src/yadism/coefficient_functions/asy/__init__.py
  src/yadism/coefficient_functions/asy/f2_cc.py
  src/yadism/coefficient_functions/asy/f2_nc.py
  src/yadism/coefficient_functions/asy/f3_cc.py
  src/yadism/coefficient_functions/asy/f3_nc.py
  src/yadism/coefficient_functions/asy/fl_cc.py
  src/yadism/coefficient_functions/asy/fl_nc.py
  src/yadism/coefficient_functions/asy/g1_nc.py
  src/yadism/coefficient_functions/asy/g1_nc_raw.py
  src/yadism/coefficient_functions/asy/kernels.py
  src/yadism/coefficient_functions/asy/partonic_channel.py
  src/yadism/coefficient_functions/asy/raw_nc.py
  src/yadism/coefficient_functions/fonll/f2_nc.py
  src/yadism/coefficient_functions/fonll/f3_nc.py
  src/yadism/coefficient_functions/fonll/fl_nc.py
  src/yadism/coefficient_functions/fonll/kernels.py
  src/yadism/coefficient_functions/fonll/partonic_channel.py
  src/yadism/coefficient_functions/heavy/f2_nc.py
  src/yadism/coefficient_functions/heavy/f3_nc.py
  src/yadism/coefficient_functions/heavy/fl_nc.py
  src/yadism/coefficient_functions/heavy/g1_nc.py
  src/yadism/coefficient_functions/heavy/g4_nc.py
  src/yadism/coefficient_functions/heavy/gl_nc.py
  src/yadism/coefficient_functions/heavy/kernels.py
  src/yadism/coefficient_functions/heavy/partonic_channel.py
  src/yadism/coefficient_functions/intrinsic/partonic_channel.py
  src/yadism/coefficient_functions/kernels.py
  src/yadism/coefficient_functions/light/kernels.py
  src/yadism/esf/esf.py
  src/yadism/input/compatibility.py
  src/yadism/input/cross_constraints.yaml
  src/yadism/input/domains.yaml
  src/yadism/input/inspector.py
  src/yadism/log.py
  src/yadism/observable_name.py
  src/yadism/output.py
  src/yadism/runner.py
  tests/yadism/cf/test_asy.py
  tests/yadism/cf/test_cc_kernels.py
  tests/yadism/cf/test_cf_partonic_channel.py
  tests/yadism/cf/test_ic.py
  tests/yadism/cf/test_matching.py
  tests/yadism/cf/test_nc_asy.py
  tests/yadism/cf/test_nc_asy_polarized.py
  tests/yadism/cf/test_nc_heavy.py
  tests/yadism/cf/test_nc_kernels.py
  tests/yadism/cf/test_pc_general.py
  tests/yadism/input/test_inspector.py
  tests/yadism/test_init.py
  tests/yadism/test_observable_name.py
  tests/yadism/test_runner.py
  tests/yadism/test_structure_function.py
Labels: physics, benchmarks

#242 Bump adani version to 0.14
  poetry.lock
  pyproject.toml
Labels: dependencies

#245 Extend benchmarks
  src/yadmark/benchmark/external/apfelpy_utils.py
Labels: benchmarks

#138 Init NNLO CC heavy quark
  extras/heavy_cc_nnlo/.gitignore
  extras/heavy_cc_nnlo/demoFelix.tar.gz
  extras/heavy_cc_nnlo/reformat/__init__.py
  extras/heavy_cc_nnlo/reformat/__main__.py
  extras/heavy_cc_nnlo/reformat/generate.py
  extras/heavy_cc_nnlo/reformat/parse.py
Labels: enhancement, physics

#239 Nix
  .envrc
  .gitignore
  .pre-commit-config.yaml
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: dependencies

#240 Drop inspector and related features
  src/yadism/input/constraints.py
  src/yadism/input/cross_constraints.yaml
  src/yadism/input/domains.yaml
  src/yadism/input/errors.py
  src/yadism/input/inspector.py
  src/yadism/runner.py
  tests/yadism/input/test_constraints.py
  tests/yadism/input/test_errors.py
  tests/yadism/input/test_inspector.py
  tests/yadism/test_runner.py
Labels: refactor

#248 remove missing contribution to heavy_components
  src/yadism/coefficient_functions/__init__.py
Labels: bug
