Repository NNPDF/yadism, pull requests merged in 2023-05, with the labels that each got.

#185 Polarized heavy coeffs
  src/yadism/coefficient_functions/heavy/g1_nc.py
  src/yadism/coefficient_functions/heavy/g4_nc.py
  src/yadism/coefficient_functions/heavy/gl_nc.py
  tests/yadism/cf/test_cfh_pol.py
  tests/yadism/cf/test_nc_asy.py
  tests/yadism/cf/utils.py
Labels: enhancement, physics

#187 Polarized FONLL coefficient functions
  docs/source/refs/cf.bib
  docs/source/shared/abbreviations.rst
  src/yadism/coefficient_functions/fonll/g1_nc.py
  src/yadism/coefficient_functions/fonll/g1_nc_raw.py
  tests/yadism/cf/test_nc_asy_polarized.py
Labels: enhancement, physics

#194 Eko 0.13
  poetry.lock
  pyproject.toml
  src/yadism/coefficient_functions/__init__.py
  src/yadism/output.py
  src/yadism/runner.py
  src/yadmark/benchmark/external/xspace_bench_utils.py
  src/yadmark/benchmark/runner.py
  tests/yadism/cf/test_coupling_constants.py
  tests/yadism/cf/test_matching.py
  tests/yadism/cf/test_nc_kernels.py
  tests/yadism/cf/test_splitting_functions.py
  tests/yadism/cf/utils.py
  tests/yadism/test_structure_function.py
Labels: dependencies

#196 Fix hera charm bottom
  extras/data/machinery/generate/HERA.py
Labels: bug

#197 Update pytest to 7.2
  poetry.lock
  pyproject.toml
Labels: dependencies

#191 Polarized matching
  src/yadism/coefficient_functions/fonll/g1_nc.py
  tests/yadism/cf/test_matching.py
Labels: physics
