Repository NNPDF/yadism, pull requests merged in 2023-10, with the labels that each got.

#233 Compute F1
  src/yadism/esf/exs.py
  src/yadism/observable_name.py
  tests/yadism/esf/test_exs.py
Labels: physics

#222 Fix polarised TMC
  extras/TMC/tmc-polarised.nb
  src/yadism/esf/tmc.py
Labels: bug

#236 Fix `F_1` implementation and allow for `g_5`
  docs/source/overview/features.rst
  docs/source/theory/fact.rst
  docs/source/theory/intro.rst
  src/yadism/esf/exs.py
  src/yadism/observable_name.py
  tests/yadism/esf/test_exs.py
Labels: refactor
