Repository NNPDF/yadism, pull requests merged in 2024-07, with the labels that each got.

#289 Deprecate info on initial states and polarized key
  poetry.lock
  pyproject.toml
  src/yadbox/export.py
  src/yadmark/benchmark/external/apfelpy_utils.py
  tests/yadbox/test_export.py
Labels: enhancement, physics

#232 Observable card generators for pDIS
  extras/data/COMPASS15/compass15_mud_g1.yaml
  extras/data/COMPASS15/compass15_mup_g1.yaml
  extras/data/COMPASS15/metadata.yaml
  extras/data/E142/e142_en_g1.yaml
  extras/data/E142/metadata.yaml
  extras/data/E143/e143_ed_g1.yaml
  extras/data/E143/e143_ep_g1.yaml
  extras/data/E143/metadata.yaml
  extras/data/E154/e154_en_g1.yaml
  extras/data/E154/metadata.yaml
  extras/data/E155/e155_en_g1f1.yaml
  extras/data/E155/e155_ep_g1f1.yaml
  extras/data/E155/metadata.yaml
  extras/data/EMC/emc_mup_g1.yaml
  extras/data/EMC/metadata.yaml
  extras/data/HERMES/hermes_ed_g1.yaml
  extras/data/HERMES/hermes_ep_g1.yaml
  extras/data/HERMES/metadata.yaml
  extras/data/HERMES97/hermes97_en_g1.yaml
  extras/data/HERMES97/metadata.yaml
  extras/data/JLABE06/jlabe06_en_g1f1.yaml
  extras/data/JLABE06/metadata.yaml
  extras/data/JLABE97/jlabe97_en_g1.yaml
  extras/data/JLABE97/metadata.yaml
  extras/data/JLABE99/jlabe99_en_g1f1.yaml
  extras/data/JLABE99/metadata.yaml
  extras/data/JLABEG1B/jlabeg1b_ed_g1f1.yaml
  extras/data/JLABEG1B/jlabeg1b_ep_g1f1.yaml
  extras/data/JLABEG1B/metadata.yaml
  extras/data/JLABEG1DVCS/jlabeg1dvcs_ed_g1f1.yaml
  extras/data/JLABEG1DVCS/jlabeg1dvcs_ep_g1f1.yaml
  extras/data/JLABEG1DVCS/metadata.yaml
  extras/data/SMC/metadata.yaml
  extras/data/SMC/smc_mud_g1.yaml
  extras/data/SMC/smc_mup_g1.yaml
  extras/data/SMCSX/metadata.yaml
  extras/data/SMCSX/smcsx_mud_g1f1.yaml
  extras/data/SMCSX/smcsx_mup_g1f1.yaml
  extras/data/machinery/generate/COMPASS15.py
  extras/data/machinery/generate/E142.py
  extras/data/machinery/generate/E143.py
  extras/data/machinery/generate/E154.py
  extras/data/machinery/generate/E155.py
  extras/data/machinery/generate/EMC.py
  extras/data/machinery/generate/HERMES.py
  extras/data/machinery/generate/HERMES97.py
  extras/data/machinery/generate/JLABE06.py
  extras/data/machinery/generate/JLABE97.py
  extras/data/machinery/generate/JLABE99.py
  extras/data/machinery/generate/JLABEG1B.py
  extras/data/machinery/generate/JLABEG1DVCS.py
  extras/data/machinery/generate/SMC.py
  extras/data/machinery/generate/SMCSX.py
  extras/data/machinery/generate/__init__.py
  extras/data/machinery/generate/utils.py
Labels: datatoolchain

#297 Update `pineappl 0.8.2`
  docs/source/implementation/kernels.rst
  docs/source/implementation/scale-variations.rst
  docs/source/implementation/structure.rst
  docs/source/overview/tutorials/compare_data.ipynb
  docs/source/overview/tutorials/getting_started.ipynb
  docs/source/theory/coeff-funcs.rst
  docs/source/theory/scale-variations.rst
  extras/fonll_hq_treatment/kDISbThr.py
  poetry.lock
  pyproject.toml
  src/yadism/esf/conv.py
  src/yadism/esf/esf.py
  src/yadism/esf/scale_variations.py
  src/yadism/esf/tmc.py
  tests/yadism/cf/test_asy.py
  tests/yadism/cf/test_splitting_functions.py
  tests/yadism/test_tmc.py
Labels: dependencies
